[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN = "your_token_here" # or add in UI/Netlify env

[[plugins]]
  package = "@netlify/plugin-nextjs"
